// <auto-generated />
using System;
//using Dal.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    //[DbContext(typeof(dbClass))]
    partial class dbClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dal.models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCareTypes")
                        .HasColumnType("int");

                    b.Property<int>("IdClients")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC078D4A93E9");

                    b.HasIndex("IdCareTypes");

                    b.HasIndex("IdClients");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("Dal.models.AvailableWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("IsAvailable")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Availabl__3214EC07B2CC71FF");

                    b.ToTable("AvailableWorkingHours");
                });

            modelBuilder.Entity("Dal.models.CareType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MinPrice")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__CareType__3214EC077D183B27");

                    b.ToTable("CareTypes");
                });

            modelBuilder.Entity("Dal.models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("email")
                        .IsFixedLength();

                    b.Property<int>("IdCareTypes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("phone")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07F9C92C00");

                    b.HasIndex("IdCareTypes");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Dal.models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Clients__3214EC07BB027F8B");

                    b.HasIndex("IdClient");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Dal.models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdAppointment")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Slots__3214EC073AC14F02");

                    b.HasIndex("IdAppointment");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Dal.models.Appointment", b =>
                {
                    b.HasOne("Dal.models.CareType", "IdCareTypesNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("IdCareTypes")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_ToCareTypes");

                    b.HasOne("Dal.models.Clients", "IdClientsNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("IdClients")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_ToClients");

                    b.Navigation("IdCareTypesNavigation");

                    b.Navigation("IdClientsNavigation");
                });

            modelBuilder.Entity("Dal.models.Client", b =>
                {
                    b.HasOne("Dal.models.CareType", "IdCareTypesNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdCareTypes")
                        .IsRequired()
                        .HasConstraintName("FK_Client_ToCareTypes");

                    b.Navigation("IdCareTypesNavigation");
                });

            modelBuilder.Entity("Dal.models.Clients", b =>
                {
                    b.HasOne("Dal.models.Client", "IdClientNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_ToClient");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Dal.models.Slot", b =>
                {
                    b.HasOne("Dal.models.Appointment", "AppointmentNavigation")
                        .WithMany("Slots")
                        .HasForeignKey("IdAppointment")
                        .IsRequired()
                        .HasConstraintName("FK_Slots_ToAppointment");

                    b.Navigation("AppointmentNavigation");
                });

            modelBuilder.Entity("Dal.models.Appointment", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Dal.models.CareType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Dal.models.Client", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Dal.models.Clients", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
